[general]
import = [
	"~/.config/alacritty/themes/themes/catppuccin_latte.toml"
]

[font]
size = 10.0

[font.bold]
family = "IosevkaTerm NFM"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm NFM"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm NFM"
style = "Italic"

[font.normal]
family = "IosevkaTerm NFM"
style = "Regular"
